#!/bin/bash

cd "$(git rev-parse --show-toplevel)"
TSLINT="node_modules/.bin/tslint"
pwd

if [[ ! -x "$TSLINT" ]]; then
  printf "\t\033[41mPlease install TSlint\033[0m (npm install tslint --save-dev)\n"
  exit 1
fi

STAGED_FILES=($(git diff --cached --name-only --diff-filter=ACM | grep ".ts$"))

echo "TSLinting ${#STAGED_FILES[@]} files"

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

$TSLINT "${STAGED_FILES[@]}"

TSLINT_EXIT="$?"

if [[ "${TSLINT_EXIT}" == 0 ]]; then
  printf "\n\033[42mCOMMIT SUCCESS\033[0m\n"
else
  printf "\n\033[41mCOMMIT FAIL:\033[0m Fix TSLint errors and try again :-)\n"
  exit 1
fi

exit $?

